alter table BNSATE04_ASIGNACION
add  B04_CUENTA_EXPEDIENTE VARCHAR2(19);
     ALTER TABLE BNSATE05_TARJETA
MODIFY B05_EMAIL VARCHAR2(50);
alter table BNSATE05_TARJETA add B05_PORCENTAJE_DISP_EFECT VARCHAR2(10 BYTE);

UPDATE BNSATE05_TARJETA 
set B05_PORCENTAJE_DISP_EFECT = 
                                    CASE 
                                            WHEN B05_USO_DISP_EFECT = 'T' THEN '10000'
                                            WHEN B05_USO_DISP_EFECT = 'N'  THEN '00000'
                                         END
										 
										 
ALTER TABLE BNSATE13_RPTA_MEF_TEMP ADD (
    B13_RUC_MEF_TEMP VARCHAR2(11 BYTE),
    B13_TIPO_TARJETA VARCHAR2(2 BYTE),
    B13_MONEDA VARCHAR2(6 BYTE)
);


ALTER TABLE BNSATE13_RPTA_MEF_TEMP MODIFY (
    B13_SEC_OPERACION VARCHAR2(20 BYTE) ,
    B13_TIPO_OPERACION VARCHAR2(3 BYTE) ,
    B13_CUENTA_CARGO VARCHAR2(20 BYTE) ,
    B13_TIPO_DOCUMENTO VARCHAR2(2 BYTE) ,
    B13_NUM_DOCUMENTO VARCHAR2(20 BYTE) ,
    B13_IMPORTE VARCHAR2(15 BYTE) ,
    B13_FEC_INICIO_AUT DATE, -- Asumiendo que esta columna representa una fecha
    B13_FEC_FIN_AUT DATE, -- Asumiendo que esta columna representa una fecha
    B13_FECHA_REGISTRO DATE -- Asumiendo que esta columna representa una fecha
);
										 
DROP PROCEDURE BNPD_00_SOLICITUD_GEN_1;
DROP PROCEDURE BNPD_13_ASIGNACION;
DROP PROCEDURE BNPD_13_ASIGNACION_ACTU;


